// ========= Copyright Open Fortress Developers, CC-BY-NC-SA ============
// Purpose: General definitions
// Author(s): ficool2, Fenteale, Kay, Ms, Cherry!
//

#pragma once

#include "shareddefs.h"
#include "mp_shareddefs.h"

// OFSTATUS: INCOMPLETE  ( labeling )
enum OF_Collision_Group_t
{
	OF_COLLISION_GROUP_UNKNOWN20 = LAST_SHARED_COLLISION_GROUP,
	OF_COLLISION_GROUP_UNKNOWN21,
	OF_COLLISION_GROUP_UNKNOWN22,
	OF_COLLISION_GROUP_UNKNOWN23,
	// OFINFO: labelled as "TFCOLLISION_GROUP_ROCKETS" in public SDK code, shared/particlesystemquery.cpp
	OF_COLLISION_GROUP_ROCKETS,
	OF_COLLISION_GROUP_UNKNOWN25,
	OF_COLLISION_GROUP_PUMPKIN_BOMB,
	// OFINFO: this is called in FireRocket + FireArrow in CPointWeaponMimic, guessing its for projectiles?
	OF_COLLISION_GROUP_PROJECTILE,
};

// Sourced from sourcemod API
#define DMG_CRIT                DMG_ACID        // < Crits and minicrits
#define DMG_RADIUS_MAX          DMG_ENERGYBEAM  // < No damage falloff 
#define DMG_NOCLOSEDISTANCEMOD  DMG_POISON      // < Don't do damage falloff too close 
#define DMG_HALF_FALLOFF        DMG_RADIATION   // < 50% damage falloff
#define DMG_USEDISTANCEMOD      DMG_SLOWBURN    // < Do damage falloff 
#define DMG_IGNITE              DMG_PLASMA      // < Ignite victim 
#define DMG_USE_HITLOCATIONS    DMG_AIRBOAT     // < Do hit location damage (sniper rifle) 

#ifdef CLIENT_DLL
#define Shared_VarArgs VarArgs
#else
#define Shared_VarArgs UTIL_VarArgs
#endif

// maybe rename to OF_ ? - cherry
// nevermind! compatibility
// nevermind again :) - cherry

#define OF_DAMAGE_CRIT_MULTIPLIER	3
#define OF_WEAPON_RANDOM_RANGE				1000.0f
#define OF_WEAPON_CRIT_CHANCE_NORMAL		0.02f
#define OF_WEAPON_CRIT_CHANCE_RAPID			0.02f
#define OF_WEAPON_CRIT_CHANCE_MELEE			0.15f
#define OF_WEAPON_CRIT_DURATION				2.0f

#define OF_PLAYER_WEAPON_COUNT 6
#define OF_PLAYER_GRENADE_COUNT 6
#define OF_PLAYER_BUILDABLE_COUNT 6

#define SF_STICKY_MAY_NOT_STICK 1<<10 // makes stickys not stick!

#define CONTENTS_TEAMRED CONTENTS_TEAM1
#define CONTENTS_TEAMBLUE CONTENTS_TEAM2

enum OFPlayerState
{
	TF_STATE_ACTIVE,
	TF_STATE_WELCOME,
	TF_STATE_OBSERVER,
	TF_STATE_DYING,
	TF_STATE_LAST
};

enum
{
	OF_TEAM_RED = FIRST_GAME_TEAM,
	OF_TEAM_BLUE,

	OF_TEAM_COUNT
};

enum
{
	OF_WEAPON_MODE_PRIMARY = 0,
	OF_WEAPON_MODE_SECONDARY,
	OF_WEAPON_MODE_COUNT
};

enum MinigunState_t
{
	OF_MINIGUNSTATE_SPINUP = 0,
	OF_MINIGUNSTATE_BEGINFIRE,
	OF_MINIGUNSTATE_FIRE,
	OF_MINIGUNSTATE_SPIN,
	OF_MINIGUNSTATE_DRYFIRE,
};

enum
{
	OF_WEAPON_TYPE_PRIMARY = 0,
	OF_WEAPON_TYPE_SECONDARY,
	OF_WEAPON_TYPE_MELEE,
	OF_WEAPON_TYPE_GRENADE,
	OF_WEAPON_TYPE_BUILDING,
	OF_WEAPON_TYPE_PDA,
	OF_WEAPON_TYPE_ITEM1,
	OF_WEAPON_TYPE_ITEM2
};

enum
{
	OF_AMMO_DUMMY,
	OF_AMMO_PRIMARY,
	OF_AMMO_SECONDARY,
	OF_AMMO_METAL,
	OF_AMMO_GRENADES1,
	OF_AMMO_GRENADES2,
	OF_AMMO_GRENADES3,
	OF_AMMO_COUNT
};

enum
{
	OF_CUSTOMDAMAGE_TYPE0,
	OF_CUSTOMDAMAGE_TYPE1,
	OF_CUSTOMDAMAGE_BACKSTAB,
	OF_CUSTOMDAMAGE_TYPE3,
};

// only these two values should exist as the others are probably econ related
enum
{
	OF_GRENADELAUNCHERTYPE_PIPE = 0,
	OF_GRENADELAUNCHERTYPE_STICKY,
};

// These values are approximate and gotten via limited testing
// using the override projectile type attribute in Live tf2
// couldn't get some of these to spawn, so for those i used the FireProjectile class as a reference
// however some i still couldnt figure out, those are marked as Unknown
// If you know a better way, feel free to update this
enum
{
	OF_PROJECTILE_TYPE_NONE = 0,		 // 0  "projectile_bullet"
	OF_PROJECTILE_TYPE_BULLET,           // 1  "projectile_bullet"
	OF_PROJECTILE_TYPE_ROCKET,           // 2  "projectile_rocket"
	OF_PROJECTILE_TYPE_PIPEBOMB,         // 3  "projectile_pipe"
	OF_PROJECTILE_TYPE_STICKYBOMB,       // 4  "projectile_pipe_remote"
	OF_PROJECTILE_TYPE_SYRINGE,          // 5  "projectile_syringe"
	OF_PROJECTILE_TYPE_FLARE,            // 6  "projectile_flare"
	OF_PROJECTILE_TYPE_JARATE,           // 7  "projectile_jar"
	OF_PROJECTILE_TYPE_ARROW,            // 8  "projectile_arrow"
	OF_PROJECTILE_TYPE_FLAMEROCKET,      // 9  Seems to be unused?
	OF_PROJECTILE_TYPE_MADMILK,          // 10 "projectile_jar_milk"
	OF_PROJECTILE_TYPE_CROSSBOW,         // 11 "projectile_healing_bolt"
	OF_PROJECTILE_TYPE_MANGLER,          // 12 "projectile_energy_ball"
	OF_PROJECTILE_TYPE_BISON,            // 13 "projectile_energy_ring" 
	OF_PROJECTILE_TYPE_STICKYJUMPER,     // 14 Defined only via items game
	OF_PROJECTILE_TYPE_CLEAVER,           // 15 "projectile_cleaver"
	OF_PROJECTILE_TYPE_UNKNOWN1,         // 16 
	OF_PROJECTILE_TYPE_CANNONBALL,       // 17 "projectile_cannonball"
	OF_PROJECTILE_TYPE_RANGER,           // 18 Defined only via items game
	OF_PROJECTILE_TYPE_ARROW_FESTIVE,    // 19 Defined only via items game
	OF_PROJECTILE_TYPE_UNKNOWN2,         // 20
	OF_PROJECTILE_TYPE_UNKNOWN3,         // 21
	OF_PROJECTILE_TYPE_JARATE_FESTIVE,   // 22 Defined only via items game
	OF_PROJECTILE_TYPE_CROSSBOW_FESTIVE, // 23 Defined only via items game
	OF_PROJECTILE_TYPE_JARATE_BREAD,     // 24 Defined only via items game
	OF_PROJECTILE_TYPE_MADMILK_BREAD,    // 25 Defined only via items game
	OF_PROJECTILE_TYPE_GRAPPLE,       	 // 26 "tf_projectile_grapplinghook"

	OF_PROJECTILE_TYPE_BALLOFFIRE,		 // 27? "tf_projectile_balloffire" Havent tried out projectile override in a while so these werent in my list
	OF_PROJECTILE_TYPE_GASPASSER,		 // 28? "projectile_jar_gas" 
	OF_PROJECTILE_TYPE_COUNT
};

enum
{
	OF_RELOAD_STAGE_NONE = 0,
	OF_RELOAD_STAGE_START,
	OF_RELOAD_STAGE_LOOP,
	OF_RELOAD_STAGE_END
};

enum
{
	OF_CLASS_UNDEFINED = 0,

	OF_CLASS_SCOUT,
	OF_CLASS_SNIPER,
	OF_CLASS_SOLDIER,
	OF_CLASS_DEMO,
	OF_CLASS_MEDIC,
	OF_CLASS_HEAVY,
	OF_CLASS_PYRO,
	OF_CLASS_SPY,
	OF_CLASS_ENGINEER,

	OF_CLASS_CIVILIAN,
	OF_CLASS_COUNT
};

// not all of these exist, compatibility only
// https://csrd.science/misc/datadump/current/tf_conds.txt
enum EOFCond
{
	OF_COND_NONE = -1,
	OF_COND_AIMING = 0,		// Sniper aiming, Heavy minigun.
	OF_COND_ZOOMED,
	OF_COND_DISGUISING,
	OF_COND_DISGUISED,
	OF_COND_STEALTHED,
	OF_COND_INVULNERABLE,
	OF_COND_TELEPORTED,
	OF_COND_TAUNTING,
	OF_COND_INVULNERABLE_WEARINGOFF,
	OF_COND_STEALTHED_BLINK,
	OF_COND_SELECTED_TO_TELEPORT,
	OF_COND_CRITBOOSTED,
	OF_COND_TMPDAMAGEBONUS,
	OF_COND_FEIGN_DEATH,
	OF_COND_PHASE,
	OF_COND_STUNNED,
	OF_COND_OFFENSEBUFF,
	OF_COND_SHIELD_CHARGE,
	OF_COND_DEMO_BUFF,
	OF_COND_ENERGY_BUFF,
	OF_COND_RADIUSHEAL,
	OF_COND_HEALTH_BUFF,
	OF_COND_BURNING,
	OF_COND_HEALTH_OVERHEALED,
	OF_COND_URINE,
	OF_COND_BLEEDING,
	OF_COND_DEFENSEBUFF,
	OF_COND_MAD_MILK,
	OF_COND_MEGAHEAL,
	OF_COND_REGENONDAMAGEBUFF,
	OF_COND_MARKEDFORDEATH,
	OF_COND_NOHEALINGDAMAGEBUFF,
	OF_COND_SPEED_BOOST,
	OF_COND_CRITBOOSTED_PUMPKIN,
	OF_COND_CRITBOOSTED_USER_BUFF,
	OF_COND_CRITBOOSTED_DEMO_CHARGE,
	OF_COND_SODAPOPPER_HYPE,
	OF_COND_CRITBOOSTED_FIRST_BLOOD,
	OF_COND_CRITBOOSTED_BONUS_TIME,
	OF_COND_CRITBOOSTED_CTF_CAPTURE,
	OF_COND_CRITBOOSTED_ON_KILL,
	OF_COND_CANNOT_SWITCH_FROM_MELEE,
	OF_COND_DEFENSEBUFF_NO_CRIT_BLOCK,
	OF_COND_REPROGRAMMED,
	OF_COND_CRITBOOSTED_RAGE_BUFF,
	OF_COND_DEFENSEBUFF_HIGH,
	OF_COND_SNIPERCHARGE_RAGE_BUFF,
	OF_COND_DISGUISE_WEARINGOFF,
	OF_COND_MARKEDFORDEATH_SILENT,
	OF_COND_DISGUISED_AS_DISPENSER,
	OF_COND_SAPPED,
	OF_COND_INVULNERABLE_HIDE_UNLESS_DAMAGE,
	OF_COND_INVULNERABLE_USER_BUFF,
	OF_COND_HALLOWEEN_BOMB_HEAD,
	OF_COND_HALLOWEEN_THRILLER,
	OF_COND_RADIUSHEAL_ON_DAMAGE,
	OF_COND_CRITBOOSTED_CARD_EFFECT,
	OF_COND_INVULNERABLE_CARD_EFFECT,
	OF_COND_MEDIGUN_UBER_BULLET_RESIST,
	OF_COND_MEDIGUN_UBER_BLAST_RESIST,
	OF_COND_MEDIGUN_UBER_FIRE_RESIST,
	OF_COND_MEDIGUN_SMALL_BULLET_RESIST,
	OF_COND_MEDIGUN_SMALL_BLAST_RESIST,
	OF_COND_MEDIGUN_SMALL_FIRE_RESIST,
	OF_COND_STEALTHED_USER_BUFF,
	OF_COND_MEDIGUN_DEBUFF,
	OF_COND_STEALTHED_USER_BUFF_FADING,
	OF_COND_BULLET_IMMUNE,
	OF_COND_BLAST_IMMUNE,
	OF_COND_FIRE_IMMUNE,
	OF_COND_PREVENT_DEATH,
	OF_COND_MVM_BOT_STUN_RADIOWAVE,
	OF_COND_HALLOWEEN_SPEED_BOOST,
	OF_COND_HALLOWEEN_QUICK_HEAL,
	OF_COND_HALLOWEEN_GIANT,
	OF_COND_HALLOWEEN_TINY,
	OF_COND_HALLOWEEN_IN_HELL,
	OF_COND_HALLOWEEN_GHOST_MODE,
	OF_COND_MINICRITBOOSTED_ON_KILL,
	OF_COND_OBSCURED_SMOKE,
	OF_COND_PARACHUTE_ACTIVE,
	OF_COND_BLASTJUMPING,
	OF_COND_HALLOWEEN_KART,
	OF_COND_HALLOWEEN_KART_DASH,
	OF_COND_BALLOON_HEAD,
	OF_COND_MELEE_ONLY,
	OF_COND_SWIMMING_CURSE,
	OF_COND_FREEZE_INPUT,
	OF_COND_HALLOWEEN_KART_CAGE,
	OF_COND_DONOTUSE_0,
	OF_COND_RUNE_STRENGTH,
	OF_COND_RUNE_HASTE,
	OF_COND_RUNE_REGEN,
	OF_COND_RUNE_RESIST,
	OF_COND_RUNE_VAMPIRE,
	OF_COND_RUNE_REFLECT,
	OF_COND_RUNE_PRECISION,
	OF_COND_RUNE_AGILITY,
	OF_COND_GRAPPLINGHOOK,
	OF_COND_GRAPPLINGHOOK_SAFEFALL,
	OF_COND_GRAPPLINGHOOK_LATCHED,
	OF_COND_GRAPPLINGHOOK_BLEEDING,
	OF_COND_AFTERBURN_IMMUNE,
	OF_COND_RUNE_KNOCKOUT,
	OF_COND_RUNE_IMBALANCE,
	OF_COND_CRITBOOSTED_RUNE_TEMP,
	OF_COND_PASSTIME_INTERCEPTION,
	OF_COND_SWIMMING_NO_EFFECTS,
	OF_COND_PURGATORY,
	OF_COND_RUNE_KING,
	OF_COND_RUNE_PLAGUE,
	OF_COND_RUNE_SUPERNOVA,
	OF_COND_PLAGUE,
	OF_COND_KING_BUFFED,
	OF_COND_TEAM_GLOWS,
	OF_COND_KNOCKED_INTO_AIR,
	OF_COND_COMPETITIVE_WINNER,
	OF_COND_COMPETITIVE_LOSER,
	OF_COND_HEALING_DEBUFF,
	OF_COND_PASSTIME_PENALTY_DEBUFF,
	OF_COND_GRAPPLED_TO_PLAYER,
	OF_COND_GRAPPLED_BY_PLAYER,
	OF_COND_PARACHUTE_DEPLOYED,
	OF_COND_GAS,
	OF_COND_BURNING_PYRO,
	OF_COND_ROCKETPACK,
	OF_COND_LOST_FOOTING,
	OF_COND_AIR_CURRENT,

	OF_COND_LAST
};

enum EOFPowerupSize
{
	OF_POWERUP_SMALL = 0,
	OF_POWERUP_MEDIUM,
	OF_POWERUP_FULL
};

enum
{
	OF_FLAGSTATUS_NONE = 0,
	OF_FLAGSTATUS_TAKEN,
	OF_FLAGSTATUS_DROPPED
};

enum
{
	OF_ITEM_UNDEFINDED = 0,
	OF_ITEM_FLAG
};

// gotta continue re'ing CCaptureFlag to figure out what's what
enum EOFFlagType
{
	TF_FLAGTYPE_CTF = 0,
	TF_FLAGTYPE_UNKNOWN1, // attackdefend.. mvm?
	TF_FLAGTYPE_UNKNOWN2,
	TF_FLAGTYPE_UNKNOWN3, // invade
	TF_FLAGTYPE_UNKNOWN4, // special delivery
	TF_FLAGTYPE_ROBOTDESTRUCTION,
	TF_FLAGTYPE_PLAYERDESTRUCTION
};

enum ETFGameType
{
	OF_GAMETYPE_UNDEFINDED = 0,
	OF_GAMETYPE_CTF,
	OF_GAMETYPE_CP,
	OF_GAMETYPE_ESCORT,
	OF_GAMETYPE_ARENA,

	//TF_GAMETYPE_MVM,
	//TF_GAMETYPE_ROBOTDESTRUCTION,
	//TF_GAMETYPE_PASSTIME,
	//TF_GAMETYPE_PLAYERDESTRUCTION,

	OF_GAMETYPE_COUNT
};

enum
{
	OF_HUDTYPE_UNDEFINDED = 0,
	OF_HUDTYPE_CTF,
	OF_HUDTYPE_CP,
	OF_HUDTYPE_PAYLOAD,
	OF_HUDTYPE_UNKNOWN4,
	OF_HUDTYPE_UNKNOWN5,
	OF_HUDTYPE_UNKNOWN6,
};

const char *GetGameTypeName(ETFGameType GameType);
const char *GetEnumGameTypeName(ETFGameType GameType);
ETFGameType GetGameTypeFromName(const char *GameName);

extern const char* sz_OFPlayerState[TF_STATE_LAST];

extern int GetBuildableId( const char *szBuildableName );

extern const char *GetAmmoName( int iAmmoIndex );

// Weapon Defines
extern const char *g_aWeaponModePrefix[OF_WEAPON_MODE_COUNT];
extern int g_aWeaponDamageTypes[];
extern const char *g_aProjectileTypeNames[OF_PROJECTILE_TYPE_COUNT];

//OFHACK: g_aAmmoNames should probably be an extern + defined somewhere but isn't
// (oh well, just bloats the exe a bit)

// No longer the case, did it properly and moved it to of_shareddefs.cpp now - Kay
extern const char *g_aAmmoNames[OF_AMMO_COUNT];

// Team Defines
extern const char *g_aTeamNames[OF_TEAM_COUNT];
extern Color g_aTeamColors[];

// health/ammo defines
extern float PackRatios[];

// Class Defines
extern const char *g_aRawPlayerClassNamesShort[];

// Map Defines
extern const char* s_ValveMaps[][3];
extern const char* s_CommunityMaps[][3];